Data #2
jonathastavares/Leaderboard pull request #2
Opened 2021-10-14 22:35 UTC by jonathastavares

This is the second milestone for my JavaScript API project, in this milestone, I added submit score and refresh board functions.

Built with:
- HTML
- CSS
- JavaScript
- Webpack

2021-10-14 23:10 UTC, sinansevgi requested changes
# Changes Required :recycle: 
------

Hi @jonathastavares, 

Good job so far!
Great use of fetch, async, and await :+1: 
There are some issues that you still need to work on to go further but you are almost there!



 ## Required Changes ♻️
_Please check the inline comments for my suggestions_ :arrow_down:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

------

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-14 23:10 UTC, sinansevgi commented on src/main.js
> +}
- [ ] Unless you need to use the `this` keyword in the scope of your function, You should stick with arrow functions. Please refactor this function with the arrow function definition.

2021-10-14 23:10 UTC, sinansevgi commented on src/index.html
> +                    <input id='score' class='input-box border' type='text' placeholder="Your score">
[Optional]

- [ ] It will be better if you have input validation. Currently, I can submit anything as a score.

2021-10-15 16:10 UTC, carlos-ssh approved these changes
Hi @jonathastavares , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved](https://user-images.githubusercontent.com/22258274/137519161-b65794ab-a739-4303-a808-65cd6c3fd1c4.gif)





Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-15 16:15 UTC, merged